name: image_uploader_app
description: "A Flutter Image Upload App with Firebase & Cubit"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.3
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  # Image Picker
  image_picker: ^1.1.2
  # UI
  cached_network_image: ^3.4.1
  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
