// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWt-TQsSkI51bNYBNxEAqbMWyZnEyvTJY',
    appId: '1:146928130789:android:89c5dd9ff615e046e7520c',
    messagingSenderId: '146928130789',
    projectId: 'image-uploader-89014',
    storageBucket: 'gs://image-uploader-89014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWt-TQsSkI51bNYBNxEAqbMWyZnEyvTJY',
    appId: '1:146928130789:ios:5a5bcec48fad8068e7520c',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'image-uploader-89014',
    iosBundleId: 'com.example.imageUploaderApp',
    storageBucket: 'gs://image-uploader-89014.firebasestorage.app',
  );
}
